# lib/mapping.py

MACRO_MAP = {
    "Águas, esgotos e drenagem": ["AAD", "AED"],
    "Ambiente": ["AMB"],
    "Arquitetura e Paisagismo": ["ARQ", "ACU", "SIN", "AEX", "TRA"],
    "Caracterização e diagnóstico": ["CAR", "SAF", "SIG", "TOP"],
    "Electricidade e Comunicações": ["IEL", "MBT", "SAC", "SLU", "INF"],
    "Estabilidade e obras de arte": ["EST", "MVT", "OAT"],
    "Gestão de Projeto": ["FIS", "FAS", "CER", "TRD", "PMO"],
    "Mecânica": ["STB", "ACV", "GAS", "HID", "PTL", "MPC"],
    "Pavimentos": ["TER", "GEO", "GET", "PAV", "VED"],
    "Segurança contra riscos de incêndio": ["SCI"],
    "Sinalização e Equipamento de segurança": ["SEG", "SHV", "SIV"],
}

DESCRICOES = {
    "CAR": "INSPEÇÃO E CARACTERIZAÇÃO",
    "FIS": "FISCALIZAÇÃO",
    "ARQ": "ARQUITETURA",
    "EST": "ESTABILIDADE, ESCAVAÇÃO E CONTENÇÃO PERIFÉRICA",
    "AAD": "INFRAESTRUTURAS ABASTECIMENTO DE ÁGUAS INTERIORES E EXTERIORES",
    "IEL": "INSTALAÇÕES ELÉTRICAS",
    "MBT": "INSTALAÇÕES DE MUITO BAIXA TENSÃO",
    "STB": "SISTEMA DE TRATAMENTO DE BAGAGEM",
    "ACV": "AR CONDICIONADO E VENTILAÇÃO",
    "GAS": "INSTALAÇÕES DE GÁS",
    "AED": "INFRAESTRUTURAS DRENAGEM",
    "SCI": "SEGURANÇA CONTRA INCÊNDIOS",
    "ACU": "ACÚSTICA",
    "TER": "COMPORTAMENTO TÉRMICO",
    "SEG": "SEGURANÇA / SECURITY",
    "SAC": "AUTOMAÇÃO E CONTROLO",
    "SIN": "SINALIZAÇÃO DE INFORMAÇÃO AO PASSAGEIRO",
    "AMB": "AMBIENTE",
    "GEO": "GEOLOGIA",
    "GET": "GEOTÉCNIA",
    "MVT": "MOVIMENTOS DE TERRAS",
    "AEX": "ARRANJOS EXTERIORES",
    "TRA": "TRAÇADO",
    "PAV": "PAVIMENTAÇÃO",
    "SHV": "SINALIZAÇÃO DIURNA",
    "SLU": "SINALIZAÇÃO LUMINOSA",
    "HID": "COMBUSTÍVEL / HIDRANTE",
    "SIV": "SEGURANÇA RODOVIÁRIA",
    "FAS": "FASEAMENTO DE OBRA",
    "SAF": "SERVIÇOS AFETADOS",
    "OAT": "OBRAS DE ARTE",
    "SIG": "SISTEMAS DE INFORMAÇÃO GEOGRÁFICO",
    "TOP": "TOPOGRAFIA",
    "CER": "CERTIFICAÇÃO AERÓDROMO",
    "INF": "ENERGIA E TELECOMUNICAÇÕES",
    "VED": "VEDAÇÕES E ACESSOS",
    "PTL": "PONTES TELESCÓPICAS",
    "MPC": "MOVIMENTADORES DE PESSOAS E CARGA",
    "TRD": "TRABALHOS DIVERSOS",
    "PMO": "GESTÃO DE PROJETO",
}
